config/routes.rb
Rails.application.routes.draw do
 

  

  root 'page#welcome'
  get "/about" => "page#about"
  get "/signup" => "users#signup", :as => "signup"
  get "/login" => "users#login", :as => "login"
  post "/create_login_session" => "users#create_login_session"
  delete "logout" => "users#logout", :as => "logout"
  resources :users, only: [:create]
  get '/issues/new' => "issues#new"
  get 'issues' => 'issues#index', :as => "issues"
  get '/issues/:id' => "issues#show", :as => "issue"
  delete 'issues/:id' => 'issues#destroy'
  post '/issues' => 'issues#create'
  get '/issues/:id/edit' => "issues#edit", :as => "edit_issue"
  patch 'issues/:id' => 'issues#update'
 
  post '/issues/:issue_id/comments' => "comments#create"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :issue
  belongs_to :user
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :comments
  before_create { generate_token(:auth_token) }
  validates :name, :email, presence: true
  validates :name, :email, uniqueness: { case_sensitive: false }
  def generate_token(column)
  begin
    self[column] = SecureRandom.urlsafe_base64
  end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  c = Comment.new
  c.username = params[:username]
  c.email = params[:email]
  c.content = params[:content]
  c.issue_id = params[:issue_id]
  c.save
  issue = Issue.find(params[:issue_id])
  redirect_to issue
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
    @issue = Issue.find(params[:id])
    @comments = @issue.comments
  end
  def destroy
    issue = Issue.find(params[:id])
    issue.destroy
    redirect_to :root
  end
  
  def new
    @issue = Issue.new
  end
  
  def create
    Issue.create(issue_params)
    redirect_to :root
  end
  def edit
    @issue = Issue.find(params[:id])
  end
  
  def update
    i = Issue.find(params[:id])
    i.update_attributes(issue_params)
    redirect_to :root
  end
  private
    def issue_params
      params.require(:issue).permit(:title, :content)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def welcome
    @issues  = Issue.all.reverse
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      cookies[:auth_token] = @user.auth_token
      redirect_to :root
    else
      render :signup
    end
  end
  def login
  end
  def create_login_session
  user = User.find_by_name(params[:name])
  if user && user.authenticate(params[:password])
    if params[:remember_me]
      cookies.permanent[:auth_token] = user.auth_token
    else
      cookies[:auth_token] = user.auth_token
    end
    flash.notice = "Login in successfully"
    redirect_to :root
    
  else
    flash.notice = "Username or password in not correct"
    redirect_to :login
  end
  end
  def logout
    cookies.delete(:auth_token)
  redirect_to :root
  end
  private
  def user_params
    params.require(:user).permit!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/_form.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for issue do |f| %>
      <dl class="form">
        <dt><%= f.label :title %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :content %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit "Update Event", :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/edit.html.erb
<%= render partial: 'form', locals: {issue: @issue} %>

app/views/issues/new.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for @issue do |f| %>
      <dl class="form">
        <dt><%= f.label :title %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :content %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit "publish new event", :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

app/views/issues/show.html.erb
<div class="issue-heading">
  <div class="container">
    <%= @issue.title %>
    <%= link_to 'Destroy', issue_path(@issue), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
    <%= link_to 'edit', edit_issue_path(@issue), class: "btn btn-primary" %>
  </div>
</div>
<div class="container">
  <div class="replies">
    <article class="reply clearfix">
      <div class="avatar">
        <%= image_tag('default_avatar.png',class:"image-circle") %>
      </div>
      <div class="body">
        <div class="heading">
          <h5 class="name"><a href="#">happypeter</a></h5>
        </div>
        <%= @issue.content %>
      </div>
    </article>
    <%= render partial: 'shared/comment_list', locals: {comments: @comments} %>
    <%= render partial: 'shared/comment_box', locals: {issue: @issue} %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Meetup</title>
 <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] + '-' + params[:action] %>">
<div class="navbar clearfix">
  <div class="container">
    <a class="navbar-brand" href="/">
      Meetup
    </a>
    <ul class="nav left">
      <li><%= link_to "about", "/about" %></li>
      <li><a href="#">placeholder</a></li>
    </ul>
    <ul class="nav right">
      <% if current_user %>
        <li><%= link_to current_user.name, "#" %></li>
        <li><%= link_to "logout", logout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "login", login_path %></li>
        <li><%= link_to "signup", signup_path %></li>
      <% end %>
    </ul>
  </div>
</div>
<%= yield %>
<% if flash.notice %>
  <div class="notice"><%= flash.notice %></div>
<% end %>
<div class="footer">
  <div class="container">
    <h2>shucheng cui 2015</h2>
  </div>
</div>
<script>
  $('.home-banner').anystretch();
</script>
</body>
</html>

app/views/page/_issue_list.html.erb
  <div class="issue-list">
    <% issues.each do |i| %>
    <article class="issue clearfix">
      <div class="avatar">
        <a href="/happypeter">
          <%= image_tag 'default_avatar.png' %>
        </a>      
      </div>
      <div class="body">
        <h5 class="title">
         <%= link_to i.title, issue_path(i) %>
        </h5>
        <a class="read-more" href="#">read</a>
        <span class="meta-data">
          <a href="/happypeter">happypeter</a>
          <%= time_ago_in_words(i.created_at) %> ago
        </span>
      </div>
      <div class="issue-comment-count">
        <i class="fa fa-comments icon-muted"></i>
         <%= link_to i.comments.count, i %>
      </div>
    </article>
    <% end %>
  </div>

app/views/page/about.html.erb
<div class="container">
  <h1>about</h1>
</div>

app/views/page/welcome.html.erb
<div class="home-banner" data-stretch="<%= image_url "home-banner-bg.jpg" %>">
  <div class="banner-inner container clearfix">
    <h1>It's Party Time!</h1>
    <p class="subheading">Come together, have a enjoyable talk</p>
    <div class="home-banner-links">
      <%= link_to "Publish New Event", "/issues/new", class: "banner-btn btn" %>
    </div>
  </div>
</div>
<div class="issue-list-header">
  <div class="container clearfix">
    <h1 class="issue-list-heading">All the Events List...</h1>
  </div>
</div>
<div class="container clearfix">
  <%= render partial: 'issue_list', locals: { issues: @issues } %>
</div>

app/views/shared/_comment_box.html.erb
<article class="reply clearfix">
  <div class="avatar">
    <%= link_to "#" do %>
      <%= image_tag "default_avatar.png", class: "image-circle" %>
    <% end %>
  </div>
  <div class="body">
  <%= form_tag("/issues/#{issue.id}/comments", method: :post) do  %>
    <%= label_tag :username, "User Name" %>
    <%= text_field_tag(:username) %>
    <%= label_tag :email, "Email" %>
    <%= text_field_tag(:email) %>
    <%= text_area_tag(:content) %>
    <%= submit_tag 'Commit Comment', class: 'btn btn-primary btn-submit' %>
  <% end %>
  </div>
</article>

app/views/shared/_comment_list.html.erb
<% comments.each do |c| %>
    <div class="reply clearfix">
       <div class="avatar">
         <%= link_to '#' do %>
           <%= image_tag 'default_avatar.png', class: 'image-circle' %>
         <% end %>
       </div>
       <div class="body">
         <div class="heading">
            <h5 class="name"><%= link_to c.username, "#" %></h5>
            <span class="datetime">
              <%= time_ago_in_words c.created_at %> ago
            </span>
         </div>
         <%= c.content %>
       </div>
    </div>
  <% end %>

app/views/users/login.html.erb
<div class="login-form-container clearfix">
  <div class="login-form">
    <%= form_tag "/create_login_session" do %>
      <dl class="form">
        <dt>
          <%= label_tag "User Name" %>
        </dt>
        <dd>
          <%= text_field_tag :name, params[:name] %>
        </dd>
      </dl>
      <dl class="form">
        <dt>
          <%= label_tag "Password" %>
        </dt>
        <dd>
          <%= password_field_tag :password, params[:password] %>
        </dd>
      </dl>
      <dl class="form remember-me">
        <%= check_box_tag :remember_me, 1, params[:remember_me] %>
        <%= label_tag :remember_me %>
      </dl>
      <p> <%= submit_tag "Login", :class => "login-button btn btn-primary" %> </p>
      <div class="need-signup">
        <%= link_to "No Account？Register", signup_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/signup.html.erb
<div class="signup-form-container clearfix">
  <div class="signup-form">
    <%= form_for @user do |f| %>
        <dl class="form">
          <dt><%= f.label :name, "User Name" %></dt>
          <dd><%= f.text_field :name %></dd>
          <% if @user.errors[:name].any? %>
            <dd class="error"><%= @user.errors[:name][0] %></dd>
          <% end %>
        </dl>
        <dl class="form">
          <dt><%= f.label :email %></dt>
          <dd><%= f.text_field :email %></dd>
          <% if @user.errors[:email].any? %>
            <dd class="error"><%= @user.errors[:email][0] %></dd>
          <% end %>
        </dl>
        <dl class="form">
          <dt><%= f.label :password, "Password" %></dt>
          <dd><%= f.password_field :password %></dd>
          <% if @user.errors[:password].any? %>
            <dd class="error"><%= @user.errors[:password][0] %></dd>
          <% end %>
        </dl>
        <dl class="form">
          <dt><%= f.label :password_confirmation, "Please Input Again" %></dt>
          <dd><%= f.password_field :password_confirmation %></dd>
          <% if @user.errors[:password_confirmation].any? %>
            <dd class="error"><%= @user.errors[:password_confirmation][0] %></dd>
          <% end %>
        </dl>
        <p><%= f.submit "Register", :class => "signup-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>